baseURL = "http://example.org/"
languageCode = "ja-jp"
title = "test Hugo Site"
theme = "docuapi"

disableKinds = ["taxonomyTerm"]

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
pygmentsUseClasses = false

defaultContentLanguage = "ja"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingIDType = "github-ascii"

[module]
[module.hugoVersion]
[[module.imports]]
# We include the theme by "../.." above, but we need one module import for Hugo to detect us as a Hugo Module.
path="github.com/bep/empty-hugo-module"

[params]
search = true
  
# Configure the language example tabs.
[[params.language_tabs]]
key = "lns"
name = "LuneScript" 
[[params.language_tabs]]
key = "lua"
name = "Lua" 
[[params.language_tabs]]
key = "shell"
name = "Shell" 

#Languages 
[languages]

[languages.ja]
languageName = "Japanese"
weight = 2
title = "LuneScript API"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [ 
# "<a href='#'>Sign Up for a Developer Key</a>",
# "Documentation Powered by [DocuAPI](https://github.com/bep/docuapi)",
# "Hugo Theme by [bep](https://github.com/bep)"
]
# [languages.ja.blackfriday]
# angledQuotes = false
# hrefTargetBlank = true
