baseURL = "http://example.org/"
languageCode = "ja-jp"
title = "公開技術情報"
theme = "hugo-theme-learn"
#themesdir = "../.."
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
defaultContentLanguage = "ja"


[params]
  #editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  description = "Documentation for Hugo Learn Theme"
  author = "Mathieu Cornic"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.ja]
title = "公開技術情報"
weight = 1
languageName = "Japanese"

# [[Languages.ja.menu.shortcuts]]
# name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
# identifier = "ds"
# url = "https://github.com/matcornic/hugo-theme-learn"
# weight = 10

# [[Languages.ja.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-camera'></i> Showcases"
# url = "showcase"
# weight = 11

# [[Languages.ja.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
# identifier = "hugodoc"
# url = "https://gohugo.io/"
# weight = 20

[[Languages.ja.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30
