# -*- coding:utf-8 -*-
#+LAYOUT: post
#+TITLE: Raspberry pi zero w で Bluetooth 色々(ファイル送受信:obex、 IP over BT:PAN )
#+TAGS: LuneScript
#+AUTHOR: ifritJP
#+OPTIONS: ^:{}
#+STARTUP: nofold

だいぶ前に買って放置していた Raspberry pi zero w をセットアップした。

Raspberry pi zero w と言えば「小型軽量」が売りなんで、
今回はポータブルな IOT デバイスとして使う事を目的として、
 Bluetooth の機能(ファイル送受信、 IP over Bluetooth) のセットアップをした。

イマドキ Bluetooth なんて、
最新のイメージでセットアップすればすぐに使えるだろうと思って余裕だったが、
実際には目的の機能が動作するまでに、かなりの時間が掛ってしまった。

少なくとも、パッケージをインストールするだけでは済まず、
いくつかのファイルを編集 & コマンド実行が必要です。


そんな訳で、次に同じことをする時のために備忘録を残しておく。


この記事で扱うメインは以下の通り。

- Raspberry pi zero w を USB 接続のみでセットアップ
- Bluetooth によるファイル送受信機能(OBEX File Transfer)の実現
- IP over Bluetooth (PAN) による、PC との SSH 接続確立

スムースにいけば、 10 〜 20分程度で完了する。
(OS イメージ書き込み後の作業時間)

なお、設定を行なうホスト環境は Ubuntu 18.04.2 LTS とする。

Ubuntu が Native で動作する PC でも、 
Windows 上の Gest OS の Ubuntu でも構わない。

* Raspberry pi zero w を USB 接続のみでセットアップ

** SD カードに OS Image を書き込む

公式サイトから OS Image を落して SD カードに書き込む。

今回は Raspbian Stretch with desktop and recommended software の
2019-04-08 を使用した。

以前 raspi で Bluetooth を扱った時、
Lite では意図する動作にならなかったトラウマがあるため、今回はこれを使用する。


イメージを書いたら、ssh と IP over USB (RNDIS) を有効化するため、
SD カードをマウントした直下の次のファイルを編集する。

- ssh
- config.txt
- cmdline.txt  
  
編集内容については、次の URL を参考に。

<https://qiita.com/mt08/items/ce5e3911d74d7fad4563#%E6%89%8B%E9%A0%86>

** RNDIS 設定

Ubuntu では、Raspberry pi zero w (以降 raspi) を
USB (2つある USB コネクタのうち、 HDMI コネクタ側の方)で接続すれば、
運が良ければ特になにもせずに IP over USB (RNDIS) の環境が確立する。

確立しているかどうかは、次の方法で確認できる。

#+BEGIN_SRC txt
$ ip a
#+END_SRC

ここで enp0s20u1 的なデバイスが表示されていて、
IP アドレスが取れていることを確認する。

IP アドレスが取れている場合、次のコマンドで raspi の IP を確認する。

#+BEGIN_SRC txt
$ ip n
#+END_SRC

同じサブネットのアドレスがあれば、それが raspi の IP。

raspi の IP が分かったら、 ssh すれば OK。

#+BEGIN_SRC txt
$ ssh -Y pi@10.42.0.100
#+END_SRC


大抵の場合、運が良くないので上記の確認では期待した結果にならない。
そのため、次のネットワーク設定が必要になる。

#+BEGIN_SRC txt
$ sudo nmtui
#+END_SRC

ここで重要なのは次。

- interface 名を enp0s20u1 *(実際のデバイス名に合せる)* 
- IP4 config を share にする
- Require IPv4 addression for this connection をチェック
  
設定後、connection を activate する。

なお、 Ubuntu では USB を接続したタイミングで connection 設定が自動で生成されるので、
不要な connection 設定は削除しておく。



上手く動作しない場合、 deactivate と activate を何度か繰り返すと解消されることがある。

ちなみに Windows をホストにする場合、野良ドライバのインストールが必要となる。


* Bluetooth によるファイル送受信機能(OBEX File Transfer)の実現

この状態でも raspi を Bluetooth でペアリング出来るし、
Bluetooth の GUI アイコンからファイル送信用の UI まで辿ることは出来る。

しかし、その ファイル送信用 UI を通してファイル送受信することはまだ出来ない。

Bluetooth のファイル送受信には、 追加で obex 系の設定が必要となる。

#+BEGIN_SRC txt
$ sudo apt install obexftp
#+END_SRC

obex 系の処理を動かすには、 bluetoothd に --compat オプションを与える必要がある。

オプションの指定は次のように /etc/init.d/bluetooth に --compat を追加する。

#+NAME: /etc/init.d/bluetooth
#+BEGIN_SRC txt
#SSD_OPTIONS="--oknodo --quiet --exec $DAEMON -- $NOPLUGIN_OPTION"
SSD_OPTIONS="--oknodo --quiet --exec $DAEMON -- --compat $NOPLUGIN_OPTION"
#+END_SRC



  
* IP over Bluetooth (PAN) による、PC との SSH 接続確立

<https://raspberrypi.stackexchange.com/questions/29504/how-can-i-set-up-a-bluetooth-pan-connection-with-a-raspberry-pi-and-an-ipod>
