~# -*- coding:utf-8 -*-
#+AUTHOR: ifritJP
#+STARTUP: nofold
#+OPTIONS: ^:{}
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="org-mode-document.css" />

#+TITLE: トランスコンパイラ LuneScript 入門 - ビルド 編

今回は LuneScript を使用したプロジェクトをビルドする方法について説明します。

LuneScript は、コマンドラインから利用するトランスコンパイラを提供しますが、
LuneScript 専用のビルドツールは提供していません。
よって、ここでは一般的なビルド方法について説明します。

* ビルド

LuneScript は Lua のトランスコンパイラですが、
LuneScript のコードそのままでも実行可能です。

例えば、次のようなソースは

#+NAME: hoge.lns
#+BEGIN_SRC lns
print( "hello" );
#+END_SRC

次のコマンドで実行することが出来ます。

#+BEGIN_SRC txt
$ lnsc hello.lns exe
#+END_SRC

しかし、これでは LuneScript から Lua へのトランスコンパイル処理が走るため、
ある程度の規模になると効率が悪くなります。

そこで、モジュール毎に Lua へトランスコンパイルするビルド管理が必要になります。

** トランスコンパイル

Lua へトランスコンパイルするには、次のコマンドを実行します。
   
#+BEGIN_SRC txt
$ lnsc hello.lns save
#+END_SRC

これにより hello.lns をトランスコンパイルし、
変換後のコードを hello.lua に出力します。

この hello.lua は Lua で実行できます。

#+BEGIN_SRC txt
$ lua hello.lua
#+END_SRC

モジュールごとにトランスコンパイルしておくだけでも
lnsc コマンドで直接実行するよりは効率良くなりますが、
まだ改善できます。

それは LuneScript の import です。

LuneScript の import は、指定のモジュールを読み込みます。
このとき、LuneScript は指定モジュールを解析します。
この解析には時間がかかります。

この解析時間を短縮する手段を提供しています。

** メタ情報ファイル

メタ情報ファイルとは、モジュールが公開しているクラスや、
そのモジュールが import している他のモジュールの依存関係などの情報を
まとめたファイルです。

import する際、モジュールを解析する代わりに
このメタ情報ファイルを読み込むことで、解析時間を短縮できます。

メタ情報ファイルは、次のコマンドで生成できます。

#+BEGIN_SRC txt
$ lnsc hello.lns SAVE
#+END_SRC

先程のコマンドと何が違うかというと、 "*save*" と "*SAVE*" の違いです。

小文字の save は、トランスコンパイルした Lua コードだけ生成しますが、
大文字の SAVE は、 Lua コードとメタ情報ファイルを生成します。

具体的には、上記コマンドを実行すると hello.lua と hello.meta が生成されます。

LuneScript はモジュールを import する際、
次の条件が全て成り立つ時に .lns ファイルの解析は行なわずに、
.meta ファイルをロードします。

- .lns に対応する .lua と .meta が存在する
- それぞれのファイルの更新時間について、次の条件を満す
  - ~.lns < .meta~
- インポート対象の mod1.lns 内で import しているモジュール mod2 の更新時間に対し、
  次の条件を満す。
  - ~mod1 > mod2~
- .meta ファイルのフォーマットバージョンが正しい


** 依存関係

あるモジュール mod2 を更新すると、
そのモジュール mod2 を import している mod1 が影響を受けます。

つまり、 mod1 と mod2 には依存関係があります。

このような依存関係があるファイルをビルドするには、
古くから make コマンドが利用されています。

make コマンドは、定義された依存関係によって、
あるファイルが修正された際、
そのファイルに依存するファイルを更新する制御を行ないます。

この依存関係を手動で定義するのは、意外と面倒なものです。

LuneScript は、 make コマンドの依存関係を自動生成する機能を提供します。


