#+TITLE: PC9801-OS/V という PC9801 シリーズ向けの OS
#+DATE: 2023-10-23
# -*- coding:utf-8 -*-
#+LAYOUT: post
#+TAGS: OS
#+AUTHOR: ifritJP
#+OPTIONS: ^:{}
#+STARTUP: nofold

そろそろ Windows12 が出ると噂されている。
自分の PC 環境は win10 が現役で、 win11 を入れる前にもう win12 なのかと、
なんとも微妙な気持ちがある。

* Windows が普及し始めた時代

ところで、今はデスクトップ PC 向け OS といえば、ほぼ windows 一択の状況である。
もちろん、 Mac 派や Linux 派の方がいるのは分っているが、
一旦ここではそれらを取り上げない。

そんな windows がここまで勢力を強めたのは、
自分が知る限り win95 あるいは win98 辺りだ。

そして、今思うと不思議なことだが、何故か PC の家電化が謳われ始め、
多くの家電量販店で PC が扱われ始めたのもこの頃だった。

OS が GUI ベースの windows になったことで、
それまでの CUI ベースの MS-DOS と比べれば格段に使い易くはなったものの、
今ほどエンタメ系の使い方が出来た訳でもない。
特にこの頃のインターネットは一般的な電話回線を使った従量課金が当たり前で、
通信速度も遅い(スマホで通信制限が掛った状態よりも遅い)し、
Web コンテンツも今と比べれば全く充実していなく、
誰でもメールを送受信できる訳でもないので、
当時の PC を有効に利用できていた家庭は少なかっただろうと思う。

そもそもこの頃は GAFA がまだない。
いや、実際には Apple は既にあったし、Amazon も創業はしている。
とはいえ、今のような様々なサービスを日本向けに提供するのはだいぶ後の話だ。

そのような環境なので、当時購入された PC の多くは埃を被っていたのが実情だろう。

そんな windows が勢力を強めた win95、win98 辺りに、国内の PC 業界に大きな変化が起った。
それは、 PC 規格の事実上の統一である。

win95、win98 登場以前は、
今考えると意外かつ様々なメーカーが独自規格の PC を発売していた。

様々な独自規格で混沌としていた PC 市場が、
win95、win98 の登場によって、PC は「windows を動かせる規格」に統一されていった。
この「windows を動かせる規格」が、いわゆる「PC/AT 互換機」と呼ばれる規格である。

なお、国産独自規格の NEC の PC-98 シリーズについては、
それまでの国産 PC のトップシェアだった、ということもあり、
NEC が PC-98 シリーズ向けに windows のカスタマイズ版を開発していたが、
それも windows2000 までで終わり、
これによって PC 規格は事実上 PC/AT 互換機に統一された。

なお、 Mac は一貫して規格統一とは別に進化を続けている。

* PC9801-OS/V

さて、ようやくここから本題である。

NEC の PC-98 シリーズの最後の OS は、 windows2000 のはずである。
しかし、ChatGPT に PC-98 シリーズの OS について聞いてみると、
「最後の OS は PC9801-OS/V だ」と言ってきた。

てっきり PC-98 シリーズの型番と勘違いしているのか？と思ったが、
OS/V という型番は PC-98 シリーズには存在しない。

では、本当に PC9801-OS/V なんていう OS が存在するのか？と調べてみたが、
どうにもネット検索ではヒットしない。

OS/V に表記が似ていなくもない OS である OS/2 の最終バージョンは、
windows2000 より前に発表なので、
OS/2 と間違えたとしても説明がつかない。

単に ChatGPT が間違っただけなのか？と思い、 Google Bard にも聞いてみたが、
やはり PC9801-OS/V は存在する OS だという。

なんとも腑に落ちない。
LLM は学習する情報が少なければ、出力する結果の精度が落ちるのは理解できる。
ただ、学習ソースが違うはずの ChatGPT と Bard で、
こんなローカルな話題について同じ間違い方をする、というのが不思議だ。

もしかしたら、PC9801-OS/V という OS は本当に存在するのだろうか？
NEC 内部のコードネームや愛称等である場合は調べようがないが、
仮にそうだとしたらそんなローカルな情報は LLM の学習に使えないので、
そもそも PC9801-OS/V という単語を覚えることもないだろう。

一番可能性があるのは、以下辺りから導き出された、と考えるのが妥当な気がする。

- PC98 シリーズには様々な型番のモデルがある
- 型番はアルファベット 2 文字のものが多い。
- 型番は / が付くことがある。
- PC/AT 互換機を DOS/V と呼ぶこともある。
- PC98 シリーズを語る際は、DOS/V を一緒に取り上げることが多い。

以上のことから、PC98 と DOS/V が強く関連付き、
PC9801-OS/V という謎の OS が生れたのではないだろうか？
