#+TITLE: Windows のマイクの音が小さい(というか無音)
#+DATE: 2023-09-02
# -*- coding:utf-8 -*-
#+LAYOUT: post
#+TAGS: Windows
#+AUTHOR: ifritJP
#+OPTIONS: ^:{}
#+STARTUP: nofold

普段ウェブ会議には使わない作業用 PC でウェブ会議をしようと思い、
会議の少し前に外付けのマイクとカメラのセットアップを開始。

しかし、カメラは設定できたものの、マイクは音が録れない状況に。

そんな訳で、今回はマイクの音が小さい(というか無音)の場合の
対処方法について。

* 結論

先に結論を書くと、以下の手順で問題解決できた。

- 「スタートメニュー」 → 「設定」→ 「プライバシー」→ 「マイク」
- 「アプリがマイクにアクセスできるようにする」をオンに設定

* 状況

- マイクは USB 接続型で、USB を指すと標準ドライバで認識される。
- コンパネ → サウンド → 「録音」タブ では
  「マイク」として認識されているが、
  マイクに向っていくら叫んでも反応なし。
- マイクのプロパティの「レベル」タブのレベルを上げても効果なし
- ダメもとで、マイクについて Windows のトラブルシューティングを
  実行したが、やはり効果無し
- 別 PC に、同じマイクを接続した場合は普通に反応する
- 同じ PC の別アカウントでも反応する

以上のことから、マイク自体は正常で、PC のドライバ自体も正常。

つまり、この PC のいつものアカウントの 
OS 設定に問題があることが判った。

* サウンド設定周り

設定を見直すために、まずはコンパネ系の設定、
コンパネ → サウンド → 「録音」タブ の設定は、
全て見直したものの効果なし。

残り何があるか？と色々と考えた結果、
「そういえばプライバシー設定で変えられたっけ？」ということで、
プライバシー設定を見ると、プライバシー設定の「マイク」項目の
「アプリがマイクにアクセスできるようにする」がオフになっていたのを発見。

この設定をオンにし、
さらに再起動もするとようやくマイクが反応するようになった。

にしても、プライバシー設定の
「アプリがマイクにアクセスできるようにする」を選択しておくと、
まさか OS のサウンド確認 UI からもボリュームの確認できないとは。。

しかも、プライバシー設定で禁止になっていることのヒントすらない。
