#+TITLE: 液晶ディスプレイメーカーのドット抜け保証
#+DATE: 2021-12-05
# -*- coding:utf-8 -*-
#+LAYOUT: post
#+TAGS: etc
#+AUTHOR: ifritJP
#+OPTIONS: ^:{}
#+STARTUP: nofold

4K ディスプレイが欲しくなったので調べものをしている。

液晶ディスプレイを選ぶ際、用途によってさまざまな観点でチェックするだろう。
しかし、誰もが気になるのは *「ドット抜け」* だろう。

そんな訳で、各メーカー毎のドット抜け保証についてまとめてみた。

* ドット抜け保証まとめ

国内で購入可能なメジャーメーカーの保証状況を以下に示す。


| 順位 | メーカー | 保証内容                                  | リンク |
|------+----------+-------------------------------------------+--------|
| 1?   | EIZO     | 1点もない (例外あり)                      | [[https://www.eizo.co.jp/support/warranty/zerobp/index.html][リンク]] |
| 2?   | ACER     | 中央に集中して3点以内、又は全面で７点以内 | [[http://www2.acer.co.jp/support/warranty/][リンク]] |
| 3?   | DELL     | 製品によって異なる。詳細は後述。          | [[https://www.dell.com/support/kbdoc/ja-jp/000126004/%E3%83%87%E3%83%AB%E3%83%87%E3%82%A3%E3%82%B9%E3%83%97%E3%83%AC%E3%82%A4%E3%83%94%E3%82%AF%E3%82%BB%E3%83%AB-%E3%82%AC%E3%82%A4%E3%83%89%E3%83%A9%E3%82%A4%E3%83%B3][リンク]] |
| 4    | IO DATA  | ドット抜け 0.001% 未満                    | [[https://www.iodata.jp/support/qa/wizard/lcd1/017.html][リンク]] |
| 5    | iiyama   | 0.001％以下                               | [[https://www.mouse-jp.co.jp/store/iiyama/support/guarantee.aspx][リンク]] |
| 6    | LG       | ドット抜け 0.01% 以下                     | [[https://www.lg.com/jp/support/support-notice-detail/JPNTC100705001001][リンク]] |
| 8    | BENQ     | 修理・交換対象外                          | [[https://www.benq.com/ja-jp/support/warranty.html][リンク]] |
| -    | ASUS     | ※保証内容を見つけられず                  | --     |

** 保証内容 1 位(？) EIZO

ドット抜け(無輝点)  は *1 点もない* ことが保証される。
ただし、黒点や光り方のムラなどは保証されない。

例えば、 *黒点が大量にあっても保証外* ということになる。
なんだかイマイチな気がする。

一応 1 位にはしたが、 *微妙なので 「1位(？)」* としている。

** 保証内容 2 位(？) ACER

次点は、 ACER の「中央に集中して3点以内、又は全面で７点以内」。
7点は多いと思うかもしれないが、
4K であれば 7 点は全体の 0.000085 % 未満なので非常に少ないと言える。

** 保証内容 3 位(？) DELL

次は DELL。 DELL はモデルによって保証内容が異なる。
一番良いモデルの保証は、 ACER と同レベルあるいは DELL の方が良いが、
そうでないモデルの場合は ACER に劣る。
よって、3 位(？) とする。

保証内容の詳細は、 上記表の ACER のリンクを参照すること。

** 保証内容 4 位 IO DATA

次は IO DATA で「ドット抜け 0.001% 未満」。

f0.001% というと、かなり少ない様に思うが、
4K だと 82 ドットとなる。
82 ドットは、これまでのメーカーと比べると桁違いに多いことが分かる。

** 保証内容 5 位 iiyama

次が iiyama で「ドット抜け 0.001% 以下」。

僅差だが、 IO DATA が 0.001% 「未満」なのに対し、
iiyama は 「0.001% 以下」となり、 iiyama は IO DATA の次となる。

** 保証内容 6 位 LG

次が LG の 「ドット抜け 0.01% 以下」。
これは酷い。
0.01% ということは 4K なら 829 ドットとなる。

いくらなんでも保証のレベルが低過ぎだろ。
大手の液晶パネルメーカーだからって、殿様商売しているんじゃなかろうか？

** 保証内容 7 位 BENQ

次は BENQ の「修理・交換対象外」。
BENQ に関しては「ドット抜けは対応しない」と明言している。
とてもじゃないが、怖くて替えない。

** 保証内容 ランキング保留  ASUS
   
最後に、 ASUS は保証内容を見つけられなかったので、判断は保留。

ただし、「保証内容を見つけ易いところに掲載していない」ということ自体、印象が悪い。

* メーカー内の品質規定

今回の調査は、ユーザクレームに対する保証だが、
メーカー内の品質規定がどうなっているのかは気になるところ。

例えば、出荷時は OK でも、
搬送途中などの衝撃によって異常が発生することは十分に考えられる。
それ以外にも、経年劣化等でドット抜けが発生こともある。

そのようなことを考えると、出荷時のドット欠け検査では、
ある程度のマージンを設けて品質チェックをしていることが考えられる。

その辺りはメーカーの内部機密なので、入手は困難だろう。

* まとめ

私の経験上、ディスプレイを使ってきてドット抜けに装具した経験は滅多にない。

『滅多にない』ということは、 逆に言えば「あった」ということでもある。
ディスプレイは常時見て作業するものなので、
そこに欠陥があると集中を妨げる要因にもなる。

4K ディスプレイはかなりお手頃価格で購入できるようになっている。
とはいえ、気軽に買い替えるほどの値段でもない。

最低限の保証を受けられるメーカーを選択するべきだろう。

ただし、現実問題、保証の規定があったとしても、
サポート窓口が反応しない、等の別問題がある可能性はあるので、
その辺りは個人で判断して欲しい。


今回の調査結果を受けて、LG と BENQ, ASUS は候補から外した。



