#+TITLE: Windows で意図しないキーボード配列(US/JIS)になった場合の確認事項
#+AUTHOR: ifritJP
#+LANGUAGE: ja
#+EMAIL: 
#+OPTIONS: ^:{}

* はじめに

私は普段 US 配列でキーボードを利用しています。

ちなみに US 配列キーボードそのものを使っているのではなく、
JIS 配列キーボードを OS 側の設定で US 配列に変更しています。
ところが先日、このキーボード配列が JIS に変っていました、

Web で対応方法を検索してみましたが、
Web に載っている方法では解決できませんでした。
なんとか数日後に原因が判明しましたが、その原因は非常にしようもないものでした。

この記事は、私と同じ現象になった方が簡単に対処できるように、
何を確認すれば良いかの記録を残すためのものです。

* 確認事項

この現象になった場合、確認すべきことは次の 2 つです。

+ Windows の レジストリの確認
+ キーボード側設定の確認

** レジストリの確認
   
Web で対処方法を検索すると、レジストリを変更する方法が紹介されています。

検索すればすぐにヒットしますが、折角なんで Qiita の記事を挙げておきます。

https://qiita.com/aoi70/items/b3e9c758d9a993d0be9a#%E3%82%AD%E3%83%BC%E3%83%9C%E3%83%BC%E3%83%89%E9%85%8D%E5%88%97%E3%82%92%E5%A4%89%E6%9B%B4-%E3%83%AC%E3%82%B8%E3%82%B9%E3%83%88%E3%83%AA%E5%A4%89%E6%9B%B4

上記設定によって、キーボードの配列を US/JIS で入れ替えることができます。

** キーボード側設定の確認

*キーボードの動作モード(iOS)を確認する*

キーボードの動作モード設定方法は機種依存です。
マニュアルで確認してください。


私のキーボードが JIS 配列になった原因は、これが原因でした。

なお、私が利用しているキーボードは bluetooth 接続です。
最近の bluetooth 接続キーボードは、
Windows だけでなく Mac や Android, iOS のマルチ OS 対応のものがあります。
私のキーボードもマルチ OS 対応のものでした。

/ただし、私はWindowsでしか使っていなかったので、このマルチ OS 対応機能は利用していませんでした。/

このマルチ OS 対応機能で、 キーボードを iOS モードに設定していると、
本来 US 配列になる筈が JIS 配列になってしまいます。

*** キーボードの仕組み

「iOS モードで JIS 配列になってしまう理由」を説明する前に、
キーボードの仕組みを簡単に説明ます。

キーボードは、キーを押すと「どのキーが押されたか」の情報を通知します。

この「どのキーが押されたか」の情報というのが少し厄介で、
"a" のキーを押した場合に通知する情報は「"a" が押された」という情報 *ではなく* 、
「キーボードのある場所のキーが押された」という情報を通知します。

この情報を *「スキャンコード」* と言います。

OS はこのスキャンコードを受け、

- スキャンコード (0x1E) は "a" のキーが押された
- スキャンコード (0x30) は "b" のキーが押された

という変換を行ないます。

そして、異なるキー配列のキーボードでも、
物理的に同じ場所に配置されているキーのスキャンコードは同じものになります。

JIS 配列の 2/" キーと US 配列の 2/@ キーのスキャンコードは同じです。

つまり OS は、スキャンコードが通知された時
そのスキャンコードが何のキーになるのかを変換しますが、
この変換にはあらかじめ設定されているキー配列(JIS/US)の情報を利用しています。

この情報が、上記のレジストリの設定そのものです。

*** キーボードの iOS モードとは

上記で説明した通り、
キーボードから通知されるスキャンコードを、
どのキーに割り当てるのかを制御するのは OS の仕事です。

しかし、 iOS はこれを US 配列固定で処理しているようです。
(全ての iOS バージョンで US 配列固定かどうかは不明です)
つまり、JIS 配列のキーボードであっても iOS では US 配列としてキーが入力されます。

これはユーザの使い勝手に問題があるため、
キーボードが送信したスキャンコードを、
OS 側の US 配列変換の結果が JIS 配列になるように、
キーボード側でスキャンコードを変換して通知するモードを搭載しています。

これが iOS モードです。

* まとめ

通常キーボードのモード切り替えには、
複数のキーの組み合わせで実現していることが多いと思います。
私の場合は、それが何かの拍子に偶然切り替わってしまい、
意図しない動作になってしまいました。

キー配列が異常になった時、
普段からキーボードのモード切り替え機能を使っている方は
原因としてキーボードのモード切り替え機能を思い付くかと思いますが、
モード切り替え機能を全く使っていなかった私には全く思い付きませんでした。

Web で検索しても、これを原因として紹介している記事はありませんでした。

この記事が、私と同じ現象に遭遇した方の助けになれば幸いです。
