#+LAYOUT: post
#+TITLE: 『エンジニア就職志望者が情報工学科に行くのは間違い』は間違い
#+TAGS: LuneScript

たまたま見つけたブログの記事で気になったものがあったので、
自分の意見を書いておきます。

* 気になったブログの記事

「エンジニア就職志望者が情報工学科に行くのは間違いです！学べることが違います！」
  
<https://www.torikun.com/entry/engineer-jouhoukougaku>

この記事を要約すると、

- 大学の情報工学科のプログラミング単位取得だけでは
  学習時間が足りないのでプログラミングスキルを上げるのは難しい。
- スキルを上げるにはプログラミングスクールがオススメ
  
というモノです。

まぁ確かに、
大学の講義・実習だけで十分なプログラミングスキルを身に付けるのは不可能であるのは事実です。

とはいえ、『エンジニア就職志望者が情報工学科に行くのは間違い』というのは、
流石に異論があります。

ブログの著者と自分とで異なる意見になる理由を考えると、

*【「エンジニア」という言葉の定義が違うから】*

だと思います。

* 「エンジニア」とは

上記の記事では、エンジニアには次の能力が必要だとしています。

- プログラミングスキル
- コミュニケーション能力
- マネジメント能力

これらは確かに重要です。

というか、「コミュニケーション能力」や「マネジメント能力」は、
エンジニアでなくても社会で働くには必要な能力です。

つまりこの著者は、

*【「エンジニア」に特化して必要な能力は「プログラミングスキル」だけ】*

と主張しているように読めます。

これは、私の考えと完全に異なります。

まず、私が考える「エンジニア」像を説明します。

*エンジニアとは、曖昧なゴールイメージを技術によってスマートな形で実現できる能力を持つ人。*

具体例を挙げると、例えば「家を建てる」というゴールイメージがあるとします。
この場合、次のような様々なことを決定し、設計書を作成して建築する必要があります。

- 建てる場所
- 予算
- 広さ
- デザイン
- 機能性
- 耐久性  
- 拡張性
- メンテナンス性  
- 建材
- 日程
- etc...

このように、
曖昧なゴールイメージを実現するために具体的な作業項目に分解し、
分解された作業の課題を洗い出し、
課題を解決し、
イメージを具現化する技術を持つのが、私が考える「エンジニア」です。

もちろん、現実には一人のエンジニアが全てを担当できる訳ではありません。

しかし、ブログの著者のような「エンジニア ＝ プログラミングスキルのある人 」では、
絶対にありません。

またブログの記事では、次の記載があります。

: 例えば、大学２年生の時にはフーリエ変換という数学の公式を習います。
: この技術はパソコンの仕組みを突き詰めて行くと重要になってくる有名な数式です。
: 微分とか積分とかいろいろ難しい公式を覚えて問題を解いていきます。
: エンジニアの方ならおわかりかと思いますが、
: エンジニアとして仕事をする上でこのフーリエ変換を使う人はぜんぜんいません。

確かに全てのエンジニアが微分・積分を使う訳ではないです。
しかし、技術の背景を知っているエンジニアと、
プログラミングしか出来ないプログラマーでは、担当できる範囲が全く違ってきます。

たとえばディープラーニングなどの技術は、
プログラミングしか出来ないプログラマーでは *絶対* に作り出すことは出来ません。
様々な知識を持つエンジニアが集結してこそ可能なものです。

* 認識が異なる理由

では、ブログの著者は何故「エンジニア ＝ プログラミングスキルのある人」という
認識なのでしょうか？

これはあくまで私の想像ですが、日本のソフトウェア開発業界の特色によるものだと思います。

その特色とは、いわゆる「ゼネコン方式」です。

大手が仕様を決め、実装を外部にアウトソーシングする。

ブログ著者にとって「エンジニア」とはアウトソーシング先であり、
「エンジニアは実装さえ出来れば良い」という思考なのではないでしょうか？

このような思考があるから、
日本のエンジニアの待遇は良くならないし、
技術レベルも世界から離される一方なのではないでしょうか？


なお、ブログ著者のプロフィールを見ると、 IBM Tokyo Lab に務めているとあります。
いわゆる大手であるのは間違いないでしょう。

* エンジニア就職志望者はどうあるべきか

私の考えは、「エンジニア就職志望者は様々な技術を学ぶべき」です。

「他人が作った仕様通りのプログラムを組んでいれば幸せ」という人は、
ブログ著者が主張するようにプログラミングスクールなりに行けば良いと思います。

ただ、日本のゼネコン方式ソフトウェア開発を請け負う、
いわゆる SIer の給与は発注元の企業よりもかなり低いのが一般的です。
それこそ IBM の半分かそれ以下ではないでしょうか？
そのことは認識しておく必要があります。


なお、エンジニア志望者が行くべきなのは、情報工学科でなくても良いと思います。

というのも、私の「エンジニア」の定義は広いので、
情報工学科では収まりきらないためです。
何を極めたいかによって、何を学ぶべきかは変ってくるでしょう。

一つだけ必須技術を上げるならば、それは *「英語」* です。

今後の「エンジニア」業界で、
日本が世界をリードすることは極一部を除いて無いでしょう。

つまり、新しい技術は海外から導入することになります。
その時、その技術の解説は英語であるのが一般的です。

英語が出来れば、いち早く技術の導入が可能になります。

英語が出来ない私が言うのもアレですが、今後の「エンジニア」には英語が必須です。
今現在でも英語は必要ですが、今後はさらに必要度が上昇します。

もしかしたら、英語よりも中国語の方が良いかもしれませんが、
それはまだ何ともいえない状況です。
