# -*- coding:utf-8 -*-
#+AUTHOR: ifritJP
#+STARTUP: nofold
#+OPTIONS: ^:{}
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="org-mode-document.css" />

#+TITLE: プログラミング教育改訂にともなうソフトウェアエンジニア業界への影響

*これはポエムです。マジなツッコミは御遠慮ください。*

アドベントカレンダーは、本来お祝いムードでするイベントだと思いますが、
「技術的ポエム」がテーマということだったので、ちょっと暗くても良いじゃない。
にんげんだもの。

* プログラミング教育改訂

数年前から話題になっていた
小、中、高校におけるプログラミング教育改訂が、もう目前に迫ってきています。

| 年度   | 対象   |
|--------+--------|
| 2020年 | 小学校 |
| 2021年 | 中学校 |
| 2022年 | 高校   |

Qiita ユーザの中にも、改訂までの残り少ないスケジュールに戦々恐々している方や、
ビジネスチャンスを虎視眈々狙っている方、
自分には関係ないと無関心の方、さまざまだと思います。

ちなみに自分としては、あまり関心の無い状態です。

そんな中でも気になるのが、
プログラミング教育改訂にともなうソフトウェアエンジニア業界への影響です。

具体的に影響とはどういうことか？というと、
プログラミング教育改訂は、
ソフトウェアエンジニアの社会的地位に多少なりとも影響するのではないか、ということです。

* ソフトウェアエンジニアの現在の社会的地位

これはあくまでも私見ですが、
現時点で日本におけるソフトウェアエンジニアの社会的地位は
決して高くない状態、むしろ社会全体平均よりも低いと思っています。

単に「ソフトウェアエンジニア」と言っても、さまざまだとは思いますが、
基本的には知的労働であることは間違いないでしょう。
一方で、「IT土方」などという言葉が出来るほど、体力勝負な面もあります。

さらに言えば、「IT土方」という割には、実際の肉体労働者よりも給料が安い場合がほとんどです。

2000 年くらいまでは 3K(きつい、汚い、危険) と言って、
土木作業に代表される肉体労働者の待遇が問題視されていましたが、
いまではソフトウェアエンジニアが「新3K(きつい、帰れない、給料が安い)」と
言われている状況です。

このような状況で、ソフトウェアエンジニアの社会的地位が高いと言える人は多くないでしょう。


もちろん、「ソフトウェアエンジニア」全てが「IT土方」的なことをしている訳ではありません。
しかし、「ソフトウェアエンジニア」が
現在のブラックを代表する業界の一つになっているのは事実としてあります。

この要因の一つが、「ソフトウェア開発に対する誤解」にあると考えています。

昔から日本には「三人寄れば文殊の知恵」や「三本の矢」に代表されるように、
組織力を重視する傾向にあります。

組織力が重要なのは間違いないでしょう。
しかしソフトウェア開発においては、 1+1 は 2 にはなりません。

もちろんこれは、 1+1 が 3 とか 4 になるという意味ではなく、
1.5 とか 1.7 になるという意味です。
そして、これは個人の能力が低いほど、この数値も下っていきます。

それなのに、経営者はとりあえず頭数を揃えればなんとかなる、と考えています。

ソフトウェア開発会社の求人情報を見ても、
「未経験者歓迎」とか書いてあるところが多くあることからみても、
いかにソフトウェアエンジニアの個人のスキルを軽視しているかが伺えます。
もちろん、待遇も決して良いものとは言えません。


Qiita は、ソフトウェアエンジニアのスキルを共有化し、
それによって各個人のスキルレベル向上を目指すのが、目的の一つだと私は認識しています。
そして、スキルを向上させることによって、
ソフトウェアエンジニアとしての価値を上げることが出来ると思っています。

しかし、残念ながら多くの会社経営者はそうは思っていないようです。

最近話題になった、
日本を代表するとある企業が人事や総務、経理などの間接部門を SE などに配置転換する、
という発表からみても、いかにソフトウェアエンジニアの専門性を軽視しているかが分かります。

日本を代表する「とある企業」ですら、この状況です。

*閑話休題*

だいぶ話が脱線してしまったので、プログラミング教育改訂の話に戻します。

* プログラミング教育改訂が与えるソフトウェアエンジニア業界への影響


プログラミング教育改訂によって、ソフトウェアエンジニア業界への影響として、
次の 2 つのパターンが考えられます。

- ソフトウェアエンジニアの社会的地位が現在より下がる
- ソフトウェアエンジニアの社会的地位が現在より上がる


この 2 つのパターンについて *妄想* すると、次のようになります。

** 社会的地位が現在より下がるパターン

ほとんどの人は、ソフトウェア開発を経験したことがありません。

そのソフトウェア開発を経験したことがない人の子供世代が、
2020 年から学校でプログラミング教育を受けるようになります。

もちろんこれは、専門学校や大学の工学部のような本格的なソフトウェア開発ということではなく、
あくまで思考法や概念などの触り程度のものになるでしょう。

しかしこれによって、その子供の親世代は次のように考えます。

「あれ？ プログラミングって自分の子供でもできるレベルなんじゃね？」

そして、これまでは
「プログラミングってなんだか良く分からないけど、
たまに変な動きをするのは『バグ』っていう、間違いで起るんだって」程度の認識だったのが、
「子供にも出来るのに、なにつまらない『バグ』なんて出してんだ？」という認識に変わります。

つまり、ソフトウェアエンジニアは
「良く分からないけど一日中 PC とにらめっこしている人」と思われていたのが、
「子供以下」にめでたくクラスチェンジです。

さらに求人も、
「プログラミングなんて小学校からやってるんだから特別な
スキルなんていらないよね。じゃぁ給料も安くて良いよね。」
となり、いま以上に待遇が悪くなります。

もちろん、全ての会社がそうなる訳ではないでしょう。
しかし、どこかの会社が下げ、そこに追従する会社が増加すれば、
業界全体に影響が波及します。

「IT土方」なんていう言葉が出来てしまったまま改善されない現在の状況を見れば、
全くの妄想であるとは否定できないのではないでしょうか？


** 社会的地位が現在より上がるパターン

一般的に良く言われる事として、
「子供の頃は親のありがたみを感じないが、自分に子供が出来ると親のありがたみが良く分かる」
というものがあります。

表現を変えると、
「人は、自分が経験していないことに対しては、正確な評価を行なうことが出来ない」
ということです。


これまでは、ソフトウェア開発を経験したことが無い人がほとんどでした。
これによって、
ソフトウェアエンジニアは「なんだか良く分からないことをやっている人」という認識に
なっていました。

しかし、今後は多少なりともプログラミングを経験することが義務化されます。

これにより、
ソフトウェアエンジニアは「なんだか良く分からないことをやっている人」から、
「ソフトウェアによって、さまざまなサービスや製品を開発している人」という認識に
クラスチェンジする可能性があります。

また、日本では長年英語教育を受けていても、英語を不得意としている人が多く、
英語が出来るというだけで一目おかれるように、
プログラミングもそのようになる可能性があります。

とはいえ、私が情報系の学生だった時代の同級生に、
プログラミングは出来るけど英語は出来ないという友人は(私を含め)多いですが、
英語は出来るけどプログラミングは出来ないという友人はいません。。。

* まとめ

プログラミング教育改訂が与えるソフトウェアエンジニア業界への影響として、
2つのパターンを挙げました。

実際にどちらのパターンになるのか？そもそも影響なんてあるのかどうか？

「来年の事を言うと鬼が笑う」なんてことわざがあるので、
1 年とちょっと先の事を言ったら鬼がへそで茶を湧かせてしまいそうなんで、
この辺りで終わりにします。
