#+TITLE: FDM 3D プリンタのスライス設定と STL エラー対策
#+DATE: 2022-12-04
# -*- coding:utf-8 -*-
#+LAYOUT: post
#+TAGS: 3d_print
#+AUTHOR: ifritJP
#+OPTIONS: ^:{}
#+STARTUP: nofold

今回も引き続き 3D プリンタ系の話です。

* 3D プリントの出来

3D プリントの出来は次で決まります。

- 3D プリンタの性能
- フィラメントの性能
- スライサーの性能

どんなに良い 3D プリンタやフィラメントを使っても、
スライサーの性能が悪い、
スライサーのパラメータの設定が正しくない場合、
意図したプリントは出来ません。

* Ultimaker cura

3D プリンタでオブジェクトをプリントするには、
3D オブジェクトを積層データ形式に変換する必要があります。

この変換処理を行なうのがスライサーです。
スライサーには幾つかの種類がありますが、
オープンソースで開発されているスライサーが Ultimaker cura です。

<https://github.com/Ultimaker/Cura>

Ultimaker cura は、3D モデルを基にスライスする専門ツールで、
モデリングは別のツールで行なう必要があります。

この記事は *ver 5.2.1* の cura を対象に書いています。

cura のバージョンが異なる場合は、この記事の内容と異なる場合があります。

* cura の設定

cura の簡易設定で Resolution を一番細かい設定にし、
Support On を選択しておけば大抵は間違いは無いですが、
それだと時間がかかり過ぎることもあります。

逆に Resolution を一番粗い設定にすれば時間は短縮できますが、
プリントをミスする可能性が出てきます。

自分が求めるプリント品質と時間を両立させには、
cura のカスタム設定でパラメータを適宜指定する必要があります。


** 主なパラメータ

cura のパラメータの内、特に重要なカテゴリは以下です。

- Quality
  - フィラメントを積層する精度を指定します
  - 細かくすれば精度は上りますが、その分時間がかかります
- Walls
  - オブジェクトの側面の構成を指定します
  - 側面の構成を変更することで、強度や見た目に影響します
- Top/Bottom
  - オブジェクトの上面、底面の構成を指定します
  - 上面、底面の構成を変更することで、強度や見た目に影響します
- Infill
  - オブジェクト内部の構成を指定します
  - 内部の構成を変更するとこで、強度に影響します
- Material
  - フィラメントの特性を指定します
  - *プリント速度を上げる場合は、*
    *フィラメントの対応温度の範囲内の上限付近に設定する方が良い傾向にあります*
- Speed
  - フィラメントのプリント速度を指定します
  - 速度を早めればプリント時間が短縮しますが、その分精度が落ちます
  - 速度はオブジェクトのパーツ毎に指定できます
  - 見た目に影響の大きい表面のプリント速度を遅くし、
    影響の少ないオブジェクト内部やサポートのプリント速度を上げるなどの調整が出来ます
  - ただし、 *影響の少ないパーツでも、*
    *速度を上げ過ぎるとプリント自体が失敗する可能性があります*
- Support
  - サポートの構成を設定します
  - サポートの剥し易さや、印刷速度に影響します
  - support placement は、サポートの配置を指定します。
    - touching buildplate は、必ずビルドプレートからサポート材を配置するようにします
    - Eveywhere は、プリントしたモデルからもサポート材を配置します。
    - *現在 touching buildplate を指定すると、*
      *本来サポートが必要な箇所にサポートが構成されずにプリントが失敗するケースがあります。*
    - touching buildplate は、モデルに余分なサポート材が付加されないため
      仕上りがキレイになるメリットがありますが、上記の通り失敗することもあるので、
      touching buildplate を利用する場合はスライス結果を十分に確認してください。

なお、 *デフォルト状態では幾つかのパラメータが非表示になっています。*

プロファイルの表示設定を変更することで、設定可能なパラメータが表示されます。

** STL エラー対策

スライサーを使う上で一番面倒なのが、モデリングデータのエラーです。

モデリングしたデータは、一見問題なさそうに思えても、
実際には問題があるケースがあります。

本来は、そのデータをモデリングしたツールでデータを修正するべきですが、
モデル公開サイトから取得したデータなどは修正が難しいことがあります。

cura は、そのような場合にエラーを修正してプリントできるようにする機能があります。


*エラー修正は、cure のパラメータカテゴリの Mesh fixes を使います。*

Mesh fixes のカテゴリ自体、 *通常だと表示されていません。*
プロファイルの表示設定を変更して Mesh fixes の項目を設定してください。

Mesh fixes は、
修正できないモデルの印刷には効果的です。
しかし、安易に使用すると意図しないプリント結果になることもあります。

*Mesh fixes を有効化してスライスした場合は、*
*実際にプリントする前にスライスした結果を確認しましょう。*

エラーのあるモデルのプリントに Mesh fixes の設定を利用した後は、
*設定を元に戻した方が良いでしょう。*


なお、MS 3D Builder を利用すると、モデリングデータのエラーを修正出来ます。
ただし、この場合もエラーが修正されただけで、
意図しない修正になっていることがあります。
実際にプリントする前に、スライスした結果を確認しましょう。
