#+TITLE: rye のインストール その 2 
#+DATE: 2024-06-01
# -*- coding:utf-8 -*-
#+LAYOUT: post
#+AUTHOR: ifritJP
#+OPTIONS: ^:{}
#+STARTUP: nofold

rye のバージョンが更新されて、インストール手順がだいぶ変ったので、
ここで再度まとめる。

なお、ここで扱う rye のバージョンは以下の通り。

: $ rye 0.34.0

* インストール

既に rye をインストール済みの場合は、
次のコマンドで一旦 rye をアンインストールしてから実行する。

: $ rye self uninstall

次の URL から、環境にあったバイナリをダウンロードする。

<https://github.com/astral-sh/rye/releases>

 
ダウンロードしたバイナリを実行すると、次のインストールステップが始まる。


- パッケージインストール方式
  - uv
  - pip
- 使用する python の選択
  - 新規インストール
  - インストール済みの python のパス指定
- rye で使用する python のバージョン指定
  - ここで 3.9 〜 3.12 までを指定できる

** パッケージインストール方式

パッケージインストール方式は、 uv の方が高速に処理できる。
ただし、互換性は pip の方が高いらしい。(いまのところ uv で問題が起きたことはない)

uv と pip は、 rye をインストールするタイミングでしか切り替えられない。
また、uv と pip を切り替えると、 
それまで rye で作っていた .venv 環境を作り直す必要がある。

具体的には次のファイル、ディレクトリを削除後に =rye sync= 仕直せばよい。

- =requirements*.lock=  
- =.venv=

** rye が利用する python のバージョン

rye で作成する環境の python のバージョンは、環境ごとに切り替えられる。
一方で、 python パッケージの依存情報を解決する際に利用する python のバージョンは、
ここで指定した python のバージョンに限定される。

python で利用したいパッケージが、
特定の python のバージョンでしか提供されていないは、
そのバージョンを指定しておく。

あるいは、 rye で作成する環境では最低限のパッケージをインストールし、
その後に python のバージョンに依存するパッケージを pip で個々にインストールする。
