#+TITLE: 自転車か原付か？
#+DATE: 2024-11-04
# -*- coding:utf-8 -*-
#+LAYOUT: post
#+AUTHOR: ifritJP
#+OPTIONS: ^:{}
#+STARTUP: nofold

2024/11/1 に改正道路交通法が施行された。

ネットでは、自転車のながら運転が禁止されたことが大々的に宣伝されている。
また、モペッドのペダルによる走行も原付扱いになることが明記されたことが
一部で話題になっている。

今回は後者について触れる。

技術系のネタではないが、自転車乗りとして気になる内容であり、
調べた内容を残しておきたかったので、ここに載せておく。

* モペッド

モペッドは、原動機を持つ二輪車で、
かつ、ペダルも付いていて人力のみでも走行可能な原動機付自転車である。

なお、人が漕がなくても原動機のみで進めるというのが、
電動アシスト自転車との一番の違いだ。

ペダルによって人力でも走行可能であるため、
人力のみで走行可能している場合は自転車として認識されているケースがあったが、
今回の道交法の改正によってモペッドをペダルによる人力走行であっても
原付扱いであることが明記された。

というのが、今回の改正の話だ。

* 道交法

ネットニュースや警察庁などの HP を見たが、
イマイチ具体的に何がどう変ったのかが分からない。
仕方がないので道路交通法の記載内容を確認する。

道路交通法は以下で確認できる。
go.jp なので間違いはないだろう。

<https://laws.e-gov.go.jp/law/335AC0000000105?tab=compare>


これを見ると、第二条の十七の記載に修正が加えられていることが分かる。

#+BEGIN_SRC txt
十七　運転　道路において、車両又は路面電車（以下「車両等」という。）を
その本来の用い方に従つて用いること（原動機に加えてペダルその他の人の力により
走行させることができる装置を備えている自動車又は原動機付自転車にあつては
当該装置を用いて走行させる場合を含み、特定自動運行を行う場合を除く。）をいう。
#+END_SRC

この 「 *原動機に加えてペダルその他の人の力により*
*走行させることができる装置を備えている自動車又は原動機付自転車にあつては*
*当該装置を用いて走行させる場合を含み* 」によって、
ペダルによる人力走行であっても、
原動機付自転車に乗っていたらそれは原付を運転していることになる。
ということを示しているのであろう。

* モビチェン

ただ、ここで疑問が出てくる。

それはモビチェンだ。

モビチェンとは、モベッドを原付と自転車に切り替え可能な機構を指すらしい。
詳しくは以下。

<https://glafit.com/content/column15/>

なお、上記記事に *「合法的に、バイクと自転車を切替て乗れる」* という記載がある。

これは、次の内容を背景にしているらしい。

<https://www.npa.go.jp/laws/notification/koutuu/kouki/kouki20210628.pdf>

上記通達には以下の記載がある。

*以下で示す２つの要件を満たすものについては、構造の切替えに応じて、*
*その車の属性、すなわち道路交通法上の車両区分を評価することとしたので、*
*周知を徹底し、遺憾のないようにされたい。*

つまり、原付と自転車が切り替わることを道交法の車両区分でも認めている、
ということだろう。

なお、この通達は 2021/6/28 に出ている。

一方で、 2024/9/4 に次の通達が出ている。
これは、今回の道交法改正に関する通達である。

<https://www.npa.go.jp/laws/notification/unei.pdf>

これには以下の記載がある。

*いわゆるペダル付き原動機付自転車を、原動機を用いずペダルのみを用いて* 
*人の力により走行させる行為が、原動機付自転車等の「運転」に該当することを*
*明確化することとした。*

ここには、ペダルのみを用いて人の力により原付を走行させても、
それは原付の運転になる、と書いている。
なお、上記の通達によるモビチェンの車両区分の
切り替えのことには記載がない。


* まとめ

今回調べた内容をまとめると、次の2つの解釈がある。

- 今回の道交法の改正は、
  ベダル付き原付をペダルのみで走行させても原付扱いになることを明記したのであって、
  モビチェンの自転車モードは道交法上自転車扱いのままであり影響ない。
- 今回の道交法の改正によって、モビチェン搭載のモベッドも原付扱いになる。

調べてみたが、
そもそもモビチェン搭載のモベッドの扱いが道交法に記載されていないため、
どちらなのかは結局よく分からない。

大事なことを、通達だけで済まさないで欲しい。
