#+TITLE: AMD AM5 マザーボードへの Windows 11 のクリーンインストール時に m.2 NVMe SSD が認識しない
#+DATE: 2025-05-25
# -*- coding:utf-8 -*-
#+LAYOUT: post
#+AUTHOR: ifritJP
#+OPTIONS: ^:{}
#+STARTUP: nofold

数年ぶりに新しい PC を組んだので OS (Win11) をクリーンインストールした。

今回組んだのは AMD の AM5 で、 OS を入れるストレージには M.2 NVMe SSD を使用。

ここで、Windows 11 をクリーンインストールする際に、
どのドライブに OS をインストールするか指定する画面が表示されるが、
期待していた M.2 NVMe SSD が表示されなかった。

代わりに
「ドライバーが見つかりませんでした。
[ドライバーの読み込み] をクリックしてください」
といった趣旨のメッセージ
 (※正確な文言は失念したが、要はドライバーがないという表示) が画面に表示された。

どうやら Windows 11 の標準インストールメディアに収録されているドライバだけでは、
この AM5 環境の M.2 NVMe SSD にアクセスできないらしい。

今回は、このケースの具体的な対応方法について書く。

なお、結論を先に書くと次になる。

- 必要なのは AM5 用の SMBus Driver である。
- Driver は AMD の公式サイトからチップセットドライバーとしてダウンロードできる。
- ダウンロードした実行ファイル (.exe) から目的の SMBus Driver 本体を取り出すには、
  別途、正常に動作している AMD CPU 搭載の Windows PC が必要になる 

* 対応方法

ネットで同様の症状を検索してみると、
Intel 向けの
ストレージコントローラードライバー (Intel VMD Technology など) に
関する話題はヒットするものの、
AMD AM5 向けの情報は、なぜかほとんど見当たらなかった。

仕方がないので、自力で解決策を探った。その手順は以下の通りだ。

- まず、以下の URL から AMD のドライバーダウンロードページにアクセスする。
  - https://www.amd.com/en/support/download/drivers.html
- 使用しているマザーボードのチップセット (例: X670E, B650 など) を選択し、
  対応する AMD Chipset Drivers をダウンロードする。
- ダウンロードしたプログラム (exeファイル) を、
  AMD CPU が搭載されている Windows PC 上で実行する。
- ここが重要で、Intel CPU の PC など、AMD CPU ではない PC で実行すると、
  次のステップで必要なドライバが展開されないことがある。
- プログラムを実行すると、通常は C:\AMD のようなフォルダが作成され、
  この中に各種ドライバが展開される。
- C:\AMD の中から、以下の 2つのファイルを含むディレクトリ を探し出す。
  - =SMBUSamd.inf=
  - =SMBUSamd.cat=
- ディレクトリは AMD_Chipset_Software\Packages\IODriver\SMBus\WTx64 のような
  階層になっていることが多いが、バージョンによって異なる可能性があるので、
  上記ファイル名で検索するのが確実。
- 上記のファイル (SMBUSamd.inf, SMBUSamd.cat) が含まれるディレクトリごとを、
  USBメモリなどのリムーバブルメディアにコピーする。
- Windows 11 のクリーンインストール画面で、「ドライバーが見つかりませんでした」の
  メッセージが表示されている状態で、
  「ドライバーの読み込み」 (または同様の) ボタンを押す。
- ドライバーの場所を指定するダイアログが表示されるので、
  先ほどリムーバブルメディアにコピーした、 =SMBUSamd.inf= と =SMBUSamd.cat= が
  含まれているディレクトリを選択する。
- なお、指定されたディレクトリからドライバを探しにいくが、
  サブレディレクトリまで探しにいってくれないので、
  必ず SMBUS_driver フォルダ (infファイルがある階層) を直接指定する必要がある。
- 正しくディレクトリを指定すると、
  ドライバーの一覧に「AMD SMBus Driver」 (またはそれに類する名前) が表示されるので、
  これを選択してインストールする。

以上で、M.2 NVMe SSD が認識され、Windows 11 をクリーンインストールできるようになるはずだ。

* まとめ

上記の通り、この対策には、
「正常に動作している AMD CPU 搭載の Windows PC が必要である」という、
少々厄介な前提条件がある。

もしもそのような PC が手元に無い場合は、以下の代替手段が考えられる。

- 一旦、SATA 接続の HDD や SSD (これらは通常、標準ドライバで認識される) に
  Windows 11 を最小構成でインストールする。
- その Windows 環境上で上記の手順を実行し、SMBus ドライバを取り出す。
- 取り出したドライバを USB メモリなどにコピーし、
  改めて M.2 NVMe SSD に Windows 11 をクリーンインストールする際に、
  そのドライバを読み込ませる。


以上。

