#+TITLE: RTX5000 シリーズで RVC を動かす
#+DATE: 2025-10-05
# -*- coding:utf-8 -*-
#+LAYOUT: post
#+AUTHOR: ifritJP
#+OPTIONS: ^:{}
#+STARTUP: nofold

RVC で音声生成 AI技術が話題になってから、
音声生成 AI のサービスが幾つか立ち上がっている。
また、サービスとして立ち上がっているくらいだから、
それらは品質もそれなり以上なんだろう。
(実際には使っていないので不明)

ただ、RVC の特徴であるローカルで動くこと、そしてオープンソースであることは
個人で遊ぶ分には非常に魅力的であるので、 RVC を動かすことに一定の需要はあるだろう。

ということで、 RVC を動かそうと思ったが github 上での最新リリース 2.2.231006 は
RTX5000 シリーズに対応していない。

- RVC 最新版
  - https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/releases/tag/2.2.231006

そこで、ソースコードを落して依存ライブラリのバージョンやコードを色々といじってみたが、
どうにもこうにも動かない。

で、困って web を探っていたところ、
オフィシャルで RTX5000 シリーズ対応版があることに気がついた。

- RTX5000 シリーズ対応版
  - https://huggingface.co/lj1995/VoiceConversionWebUI/blob/main/RVC20240604Nvidia50x0.7z

なお、上記を使ってトレーニングから推論までを簡単に試したところ、
推論で使用するアルゴリズムに rmvpe を指定するとエラーで動かなかったが、
別のアルゴリズムにすると最後まで動くところまでは確認できた。

ということで、 RTX5000 シリーズの人は上記を使うと良い。

--------

それにしても、
RTX5000 シリーズは Compute Capability が一足飛びに変ってしまったため、
ちょっと古いツールは動かなくなってしまっていることが多い。

直近の RTX シリーズの Compute Capability は、以下になっている。

- RTX3000 シリーズ が 8.6
- RTX4000 シリーズ が 8.9
- RTX5000 シリーズ が 12.0
   (RTX5000 シリーズを正常に動作させるには Cuda Toolkit 12.8 以降が必須)


RTX5000 シリーズは、コスパ的にも互換性的にも現時点では全くオススメできない GPU だ。
とはいえ、現時点で購入可能なミドルレンジ以上の GPU は RTX5000 シリーズしかないので、
これを買うしかないのだが。

また、 AMD の GPU では別問題で AI 系を動かすのが一苦労だし。

RTX5000 で唯一マシなことは、
近年の殿様商売の GeForce シリーズの割には、 
2025/7 から現時点において随分と安くなっているということ。

安くなっているといっても、RTX4000 シリーズに比べれば高い。
あくまでも、RTX5000 シリーズの発売当初に比べて安いということ。
